#ifndef VERSION_H
#define VERSION_H

#define ANAGA_VERSION_FULL_HEX 0x00000001
#define ANAGA_VERSION_MAJOR ((ANAGA_VERSION_FULL_HEX >> 24) & 0xFF)
#define ANAGA_VERSION_MINOR ((ANAGA_VERSION_FULL_HEX >> 16) & 0xFF)
#define ANAGA_VERSION_PATCH ((ANAGA_VERSION_FULL_HEX >> 8) & 0xFF)
#define ANAGA_VERSION_BUILD (ANAGA_VERSION_FULL_HEX & 0xFF)

void print_kernel_version(void);

#endif
